name: choi_pos
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.8
  go_router: ^14.6.1
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  scrollable_table_view: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/choi-image.png
    - assets/choi-user.png
    - assets/choi-client.png